export type IconPropsType = {
  width?: number;
  height?: number;
  color?: string;
  stroke?: string | number;
};

export * from "./arrow-right-up";
export * from "./arrow-left";
export * from "./arrow-right";
export * from "./close";
export * from "./menu";
export * from "./caret-down";
export * from "./instagram";
export * from "./facebook";
export * from "./arrow-circle-up-right";
export * from "./person";
export * from "./partner";
export * from "./volunteer";
export * from "./thank-you-illustration";
export * from "./brainstorm-illustration";
export * from "./search";
export * from "./chevronlefticon";
export * from "./chevronrighticon";
export * from "./facebook-colored";
export * from "./instagram-colored";
export * from "./x-colored";
export * from "./gmail-colored";
export * from "./verified";
export * from "./volunteering";
export * from "./events";
export * from "./calendar";
export * from "./charity";
export * from "./fundraising";
export * from "./phone";
export * from "./mail";
export * from "./log-out";
export * from "./globe";
export * from "./category";
export * from "./newspaper";
export * from "./settings";
export * from "./map-pin";
export * from "./pencil-simple";
export * from "./warning-circle";
